[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
BurgersEquation = "2685da08-9f13-4009-b709-356dd418f2d4"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
CodecBzip2 = "523fee87-0ab8-5b00-afb7-3ecf72e48cfd"
CodecLz4 = "5ba52731-8f18-5e0d-9241-30f10d1ec561"
CodecXz = "ba30903b-d9e8-5048-a5ec-d1f5b0d4b47b"
CodecZlib = "944b1d66-785c-5afd-91f1-9de20f533193"
CodecZstd = "6b39b394-51ab-5f42-8807-6242bab2b4c2"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DiffResults = "163ba53b-c6d8-5494-b064-1a9d43ac40c5"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
ImplicitAD = "e7cbb90b-9b31-4eb2-a8c8-45099c074ee1"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LineSearches = "d3d80556-e9d4-5f37-9878-2ab0fcc64255"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
ReverseDiff = "37e2e3b7-166d-5795-8a7a-e32c996b4267"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
TranscodingStreams = "3bb67fe8-82b1-5028-8e26-92a6c54297fa"
Wavelets = "29a6e085-ba6d-5f35-a997-948ac2efa89a"

[sources]
BurgersEquation = {path = "BurgersEquation"}
ImplicitAD = {path = "ImplicitAD"}
